server:
  port: 8080

spring:
  datasource:
    url: null
    username: null
    password: null
  sql:
    init:
      schema-locations: classpath*:db/mysql/schema.sql
      data-locations: classpath*:db/mysql/data.sql
      mode: ALWAYS
